version: 0.0
os: linux
files:
  - source: /dist
    destination: /data/mobi-otc-admin/dist
  - source: /ansible
    destination: /data/mobi-otc-admin/ansible
  - source: /appspec.yml
    destination: /data/mobi-otc-admin/
permissions:
  - object: /data
    pattern: "mobi-otc-admin"
    owner: nginx
    group: root
    mode: 554
    type:
      - directory
  - object: /data/mobi-otc-admin
    pattern: "dist"
    owner: nginx
    group: root
    mode: 554
    type:
      - directory
  - object: /data/mobi-otc-admin/dist
    pattern: "**"
    owner: nginx
    group: root
    mode: 664
    type:
      - file
  - object: /data/mobi-otc-admin/ansible/scripts
    pattern: "**"
    owner: nginx
    group: root
    mode: 755
    type:
      - file
hooks:
   AfterInstall:
       - location: ansible/scripts/after_install.sh
         timeout: 3600

